//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.30 at 03:17:59 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soapexample.com/spring/soap/api/loanEligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javatechie.spring.soap.api.loaneligibility;
